[package]
name = "testapi"
version = "0.1.0"
edition = "2021"

[dependencies]
comfy-table = "7.1"
serde_json = "1.0"
termion = "2.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[dependencies.librus-rs]
path = ".."
